### PR TITLE
Initial commit for CI

### PR DESCRIPTION
**Pull request by harshpavuluri**
Merging this into master to test CI pipeline

### CODE REVIEW

**Comment by harshpavuluri** [comment]
@ManthanKeim Take a look at the YAML file and let me know if I have to fix anything in the build commands. The current ones I made failed to build in the enviorment in Github Actions. (See below)

**Review by harshpavuluri — COMMENTED** [review]
Updated a file, was treating warnings as errors. Build was able to be completed, but because no tests exist, NPM test failed

**Comment by ManthanKeim** [comment]
We'll have to make our own tests ?

**Comment by harshpavuluri** [comment]
> We'll have to make our own tests ?

Yes lol

**Pull request merged**
